# Generated by Django 5.0.3 on 2024-03-05 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_note_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='titlenote',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
